services:
  db-store:
    image: postgres:16
    environment:
      - POSTGRES_DB=dev-store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
      - ./postgresql-init:/docker-entrypoint-initdb.d
    ports:
      - "7676:5432"

  web:
    build: .
    env_file:
      - ./store/.env
    volumes:
      - ./:/usr/src/store
    environment:
      - DATABASE_URL=psql://postgres:postgres@db-store:5432/dev-store
    ports:
      - "8002:8002"
    depends_on:
      - db-store

volumes:
  posgress: