# Generated by Django 5.0.6 on 2024-06-14 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_baseproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
