# Generated by Django 5.0.6 on 2024-06-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_baseproduct_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
